### ISSUE TITLE
gopkg.in/yaml.v2 can't unmarshal into `vf.MutableMap`

### ISSUE THREAD

**Issue by hunner** [lyraproj/dgo#7]
This may be a red herring, but I'm just recording it for posterity and hopefully it uncovers something.

Our project is using `gopkg.in/yaml.v2` and I couldn't get the following to work:
```go
yaml := `version: 1.0
description: description

variables:
  - name: value

`
payload := vf.MutableMap(nil)
yaml.Unmarshal(yaml, payload)
```
The payload was always entirely unchanged, and doing `sType.Validate(nil, payload)` always returned no errors, even though some keys were marked as `required: true` in the spec yaml.

It all works when using `gopkg.in/yaml.v3`

**Comment by thallgren** [comment]
This is a problem related to how yaml.v2 and yaml.v3 implement custom marshaling. In yaml.v2, an object that implements the `Unmarshaler` interface with an `UnmarshalYAML` function. The signature of those functions are different. In yaml v2 it looks like this:
```
  UnmarshalYAML(unmarshal func(interface{}) error) error
```
whereas in yaml.v3, the same method has the signature:
```
  UnmarshalYAML(n *yaml.Node) error
```
Since the methods have the same name, and since parameter overloads isn't permitted in Go, it's impossible to support both.

From a design perspective, dgo is left with the following alternatives:
1. Remove support for yaml completely from the dgo module and instead add a separate modules, one for yaml.v2 and one for yaml.v3. Unfortunately, this solution will be more complex than the current one since it's impossible to just add another interface to an already existing type.
2. Choose yaml.v3 and require that consumers also use that when unmarshaling dgo values. It is possible to use both at the same time. You can always do:
    ```
    import y3 "gopkg.in/yaml.v3"
    ...
    payload := vf.MutableMap(nil)
    y3.Unmarshal(yaml, payload)
    ```
3. Use v2 instead of v3. This is the least attractive alternative. Many bugs have been fixed in v3 and the v3 parser provides an AST with
line and column information which vouches for more accurate and helpful error messages when parsing dgo type strings.

**Comment by thallgren** [comment]
For several reasons, I think it's best to move the dgo yaml support into a module of its own as proposed in #8. By doing so, dgo can be used in situations where yaml is not required at all and projects that want to stick with yaml.v2 and still use dgo can do that without also introducing yaml.v3 into the dependency mix.

Using yaml.v2 should be simple. This code can be used to replace the example above and should give the same results:
```
var iv interface{}
yaml.Unmarshal(yaml, &iv)
payload := vf.Value(iv).(vf.Map)
```

The only known drawback using yaml this way instead of using the dgoyaml package is that dgo specific values that rely on tags will not be recognized. Some well known tags such as !!binary and !!timestamp will be recognized (at least in yaml.v3) but dgo specific tags will not. No big deal unless you're serializing a sensitive value or a dgo type.
